apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:update-deployments
  namespace: ns1

rules:
- apiGroups:
  - apps
  resources:
  - deployments 
  verbs:
  - update
