apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-role-binding
subjects:
- kind: ServiceAccount
  name: kyverno-service-account
  namespace: kyverno
roleRef:
  kind: ClusterRole
  name: kyverno:update-deployments
  apiGroup: rbac.authorization.k8s.io
