apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kyverno:update-deployments
  namespace: ns1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno:update-deployments
subjects:
- namespace: kyverno
  kind: ServiceAccount
  name: kyverno
- namespace: kyverno
  kind: ServiceAccount
  name: kyverno-background-controller